deploy:
  provider: pypi
  user: akesterson
  password:
    secure: RlZ3kw0x7/5QNBUIqj5wjkpS11TuSdH7o1S41m4Vea8HiryQjB2+CFf+uBXj8nb1OtYDRaeKTSnk3qVlUvaUglFd7sV+Hh2DDo4pYomd0xDFHnK2LB+hzbYftkOptmwdS2bc0X7vr+xdY+7b2DPTlyowrs3Xp2WvzRWM4hWnA3Q=
  true:
    tags: true
    branch: master
sudo: false
language: python
python:
- '3.6'
- '3.8'
- pypy3
install: travis_retry pip install tox-travis
script: tox
